---
- name: Configurar servidor de aplicação Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapp"
    - dbpassword: "devopsmaonamassa"
  tasks:
    - name: Adicionar usuario de app
      user:
        name: app
        comment: Usuário de aplicação
        uid: 500

    - name: Instalação do git client
      yum:
        name: git
        state: latest
    - name: Instalaçao do Java
      yum:
        name: java-11-openjdk-devel
        state: latest

    - name: Download do Maven
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz
    
    - name: Unzip do pacote maven
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Criação de diretório de app
      file: 
        path: /opt/notes
        state: directory
        owner: app
        group: app
        mode: 0755

    - name: Configurar o Maven no perfil
      copy:
       content: 'export PATH=$PATH:/usr/share/maven/bin'
       dest: /etc/profile.d/maven.sh

    - name: Carregar o perfil atual
      shell: source /etc/profile
      become: yes

    - name: Clone do repositório notes - app
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes

    - name: Configurar arquivo pom.xml com reposotorios maven centro
      template:
        src: pom.xml
        dest: /opt/notes/pom.xml

    - name: Configurar arquivo de propriedades para a camada de banco de dados
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties

    - name: Gerar pacote da aplicação
      command: /opt/apache-maven-3.1.0/bin/mvn -f /opt/notes/pom.xml package
      become_user: app
      become: yes

    - name: Registrar versão atual do pacote
      command: "/opt/apache-maven-3.1.0/bin/mvn -q org.apache.maven.plugins:maven-help-plugin:2.5.5:evaluate -Dexpression=project.version | grep -v '\\[)'"
      args:
        chdir: /opt/notes
      register: app_version
      changed_when: false

    - name: Debug app_version
      debug:
        var: app_version.stdout

    - name: Configurar serviço do Systemd
      template:
       src: etc/systemd/system/notes.service
       dest: /etc/systemd/system/notes.service
      vars:
        app_version: "{{ app_version.stdout }}" 
      notify: reload daemon

    - name: Iniciar serviço notes
      service:
        name: notes
        state: restarted
    
  roles:
    - configuracao-default-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'

    - name: reload daemon
      systemd:
        daemon_reexec: yes